CREATE TABLE BIZFRAME_CAMEL_AGENT (
	AGENT_ID		VARCHAR(100) NOT NULL,
	LABEL			VARCHAR(200)
	JOLOKIA_URL      VARCHAR(500),
	JMX_URL          VARCHAR(500),
	TO_LIST          VARCHAR(500),  
	TIMESTAMP		TIMESTAMP DEFAULT CURRENT TIMESTAMP  NOT NULL,
	CONSTRAINT BIZFRAME_CAMEL_AGENT_PK PRIMARY KEY (AGENT_ID)
);
